const assert = require('assert');
const fs = require('fs');

const sidebar = fs.readFileSync('templates/components/sidebar.html', 'utf8');
const profile = fs.readFileSync('templates/views/perfil.html', 'utf8');
const script = fs.readFileSync('static/js/profile.js', 'utf8');
const styles = fs.readFileSync('static/css/profile.css', 'utf8');
const careers = JSON.parse(fs.readFileSync('static/data/udp-careers.json', 'utf8'));

assert.match(sidebar, /<button[^>]+id="auth-profile"[^>]+onclick="abrirPerfil\(\)"/);
assert.match(sidebar, /id="auth-avatar"/);
assert.match(sidebar, /id="auth-name"/);
assert.match(sidebar, /id="auth-email"/);
assert.doesNotMatch(sidebar, /auth-reset-data|auth-logout|push-settings-open/);
for (const id of ['tab-perfil', 'profile-account-type', 'profile-career-input', 'profile-career-save', 'profile-sharing-toggle', 'push-settings-inline', 'profile-community-directory', 'auth-reset-data']) {
  assert.ok(profile.includes(`id="${id}"`), `profile view should contain ${id}`);
}
assert.match(profile, /id="auth-reset-data" class="profile-action-row is-danger"/);
assert.match(script, /user.app_metadata && user.app_metadata.portal_role === 'admin'/);
assert.ok(script.includes("accountType.textContent = isAdmin ? 'CUENTA ADMINISTRADORA' : 'CUENTA PERSONAL'"));
assert.match(styles, /\.profile-hero\.is-admin-account \.profile-hero-topline/);
assert.match(styles, /\.profile-hero\.is-admin-account \.profile-hero-mark/);
assert.match(profile, /id="profile-career-save"[^>]*aria-live="polite"[^>]*>[\s\S]*profile-career-save-icon[\s\S]*profile-primary-button-label/);
assert.doesNotMatch(profile, /profile-career-save-(check|spinner|error)/);
assert.match(profile, /class="profile-action-row is-signout"/);
assert.doesNotMatch(profile, /Configurar notificaciones|Ver perfiles compartidos|push-settings-open|abrirPerfilesComunidad\(\)/);
assert.doesNotMatch(profile, /id="push-(classes|agenda)-toggle"|class="push-option"/);
assert.doesNotMatch(profile, /push-test-example|<select[^>]*push-/);
assert.match(profile, /id="push-enable-toggle"/);
assert.ok(profile.indexOf('profile-career-card') < profile.indexOf('profile-community-card'), 'community card should follow career in the mobile document flow');
assert.match(styles, /grid-template-areas: "community career" "community privacy" "community notifications" "data signout"/);
assert.match(styles, /grid-template-areas: "career" "community" "privacy" "notifications" "data" "signout"/);
assert.match(styles, /@media \(min-width: 761px\) \{ \.profile-settings-grid \{ align-items: start; \} \.profile-community-card \{ align-self: stretch; \} \}/);
assert.match(styles, /\.profile-page \.push-dialog-status \{[^}]*font-family: inherit; font-size: 9px; line-height: 1\.4;/);
assert.doesNotMatch(profile, /push-test|push-example|push-remove-button/);
assert.match(script, /updateUserMetadata\(\{ career:/);
assert.match(script, /setCareerSaveButton\('Guardando…', 'loading'\)/);
assert.match(script, /setCareerSaveButton\('Carrera guardada', 'success', 2000\)/);
assert.match(script, /setCareerSaveButton\('No se pudo guardar\. Revisa tu conexión e inténtalo de nuevo\.', 'error', 3200\)/);
assert.match(script, /careerSaveIconPath\.setAttribute\('d', 'M12 3a9 9 0 1 0 9 9'\)/);
assert.match(script, /careerSaveIconPath\.setAttribute\('d', 'M12 9v4m0 4h\.01M10\.3 3\.9/);
assert.doesNotMatch(script, /careerSave(Check|Spinner|Error)/);
assert.doesNotMatch(script, /setFeedback\('Carrera guardada en tu perfil\.'/);
assert.match(script, /\.select\('share_information'\)\.eq\('id', user\.id\)/);
assert.match(script, /\.update\(\{ share_information: nextValue \}\)\.eq\('id', currentAuth\.user\.id\)/);
assert.match(script, /textContent = item\.name/);
const civilEngineeringCareers = careers.filter(item => item.name.normalize('NFD').replace(/[\u0300-\u036f]/g, '').toLocaleLowerCase('es').startsWith('ingenieria civil'));
assert.strictEqual(careers.length, 5, 'the catalog itself should contain only Civil Engineering programs');
assert.strictEqual(civilEngineeringCareers.length, 5, 'the profile selector should offer only Civil Engineering programs');
assert.ok(civilEngineeringCareers.some(item => item.name === 'Ingeniería Civil en Ciencia de Datos e Inteligencia Artificial'));
assert.match(script, /careerId: career\.id/);
assert.match(script, /portal:career-changed/);
assert.match(script, /function clearSavedCareerForSearch\(\)/);
assert.match(script, /let careerSearchOriginalValue = null/);
assert.match(script, /if \(!open && careerSearchOriginalValue !== null\) \{[\s\S]*careerInput\.value = careerSearchOriginalValue;[\s\S]*careerSearchOriginalValue = null/);
assert.match(script, /careerSearchOriginalValue = null;\s*setCareerMenuOpen\(false\)/);
assert.match(script, /careerInput\.addEventListener\('focus',[\s\S]*clearSavedCareerForSearch\(\)[\s\S]*setCareerMenuOpen\(true\)/);
assert.match(script, /careerInput\.addEventListener\('click',[\s\S]*clearSavedCareerForSearch\(\)[\s\S]*renderCareerOptions\(\)/);
assert.match(script, /savedCareerId = savedCareer \? savedCareer\.id : null/);
assert.strictEqual(careers.find(item => item.id === 'ingenieria-civil-industrial').school, 'EII');
assert.strictEqual(careers.find(item => item.id === 'ingenieria-civil-en-obras-civiles').school, 'EOC');
assert.strictEqual(careers.find(item => item.id === 'ingenieria-civil-plan-comun').school, null);
assert.strictEqual(careers.find(item => item.id === 'ingenieria-civil-plan-comun').durationYears, 1);
assert.match(script, /avatarWords\[avatarWords\.length - 2\]/);
assert.match(fs.readFileSync('static/js/auth.js', 'utf8'), /words\[words\.length - 2\]/);
assert.match(fs.readFileSync('static/js/community_schedules.js', 'utf8'), /words\[words\.length - 2\]/);
assert.match(styles, /@media \(max-width: 760px\)/);
assert.match(styles, /@media \(max-width: 600px\)/);
assert.match(fs.readFileSync('static/js/push_notifications.js', 'utf8'), /getElementById\('push-settings-inline'\)/);
assert.doesNotMatch(fs.readFileSync('static/js/push_notifications.js', 'utf8'), /push-settings-open|push-settings-dialog/);
assert.match(fs.readFileSync('static/js/push_notifications.js', 'utf8'), /JSON\.stringify\(\{ classes: true, agenda: true \}\)/);
assert.doesNotMatch(fs.readFileSync('static/js/push_notifications.js', 'utf8'), /\/test|sendTestNotification|TEST_EXAMPLES/);
assert.match(fs.readFileSync('static/js/push_notifications.js', 'utf8'), /getElementById\('push-enable-toggle'\)/);
assert.match(fs.readFileSync('static/js/push_notifications.js', 'utf8'), /async function deactivate/);
assert.match(fs.readFileSync('app/services/push_notifications.py', 'utf8'), /VALUES\(\?,1,1,\?\)/);
assert.match(fs.readFileSync('static/js/community_schedules.js', 'utf8'), /renderInlineDirectory\(directory/);
console.log(`profile-settings: profile controls, civil-engineering options (${civilEngineeringCareers.length}), and privacy scope verified`);
